import styles from './BodyHome.module.css';

const BodyHome = (props) => {
  //   console.log(props);
  return (
    <main className={styles.main}>
      <p>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aut, ipsa voluptatem quam nam enim tempora dolorum tempore dicta doloremque fugit, magni omnis repellat, exercitationem aperiam reprehenderit corporis dolor. Nesciunt, amet. Ipsum eos iure nam ipsam! Harum hic, quas neque iste possimus esse rem, voluptates qui quasi animi, ducimus ut deserunt magnam dolore aut! Impedit, quidem ab ex adipisci delectus error. Odit maxime deserunt nobis reprehenderit exercitationem necessitatibus
        fuga itaque repudiandae quis delectus fugit odio vitae eaque est qui recusandae, voluptate ea nemo consequuntur quaerat tempore maiores. Soluta praesentium quisquam laudantium? Alias, ad rem mollitia ut minus deserunt tempore assumenda quae, ducimus dolore voluptate molestias. Sunt perferendis quidem, magni minima quia officia rem accusamus error nisi sapiente natus, consequuntur molestiae aut! Aperiam molestiae neque, est consectetur voluptates earum eos deserunt repellat incidunt,
        eaque iure temporibus aspernatur perspiciatis magni aliquam ab ratione similique sequi! Suscipit laborum aut eveniet est, odit quas incidunt. Sequi, magnam! Tempora molestiae ex obcaecati repellendus, autem itaque. Libero delectus tempora quidem nulla inventore autem veniam, odio blanditiis ullam nihil officia nesciunt nam excepturi! Sed excepturi obcaecati voluptates repellendus! Hic magnam modi quaerat nisi consequuntur saepe placeat porro corporis quas dolor voluptates error quis
        tempore, totam adipisci reprehenderit aspernatur officiis rerum quia molestias, numquam incidunt odio. Saepe, impedit architecto. Cumque, nam, adipisci, delectus praesentium possimus quasi totam veritatis quas numquam quisquam atque necessitatibus corporis! Animi vel voluptas tenetur ex reprehenderit, illum aut labore sint. Ex doloribus nostrum dignissimos quia. Assumenda perferendis ab atque ratione facilis sit sint non, labore aperiam tempore magni, quidem illum quod adipisci deleniti
        optio distinctio cum nemo dolorem sapiente doloremque iste cupiditate quibusdam excepturi? Vero. Neque deleniti maxime vero sint error illum eius iste hic architecto cum quaerat quidem, doloribus, commodi officia odit dolor. Libero culpa quidem voluptate eos porro perferendis deleniti dignissimos laudantium neque! Veniam at explicabo fuga quas sit praesentium sunt iure neque ducimus nobis! Minima necessitatibus provident dolor quas eveniet, illum modi? Numquam quasi aperiam tempora
        explicabo velit ducimus, suscipit ut laborum! Magnam cum, qui quod odio tempora ducimus eaque? Amet excepturi dolorem quos, impedit sapiente corrupti laudantium vel nesciunt quaerat eligendi obcaecati fuga similique. Voluptatem a numquam nulla hic dolore officia! Commodi, reiciendis blanditiis. Fuga quidem quia, distinctio, ex mollitia impedit, eaque dolorum vel similique et fugiat. Sunt cum possimus corporis earum laudantium numquam ipsum incidunt, hic eius modi vitae! Dicta? Sed
        inventore perferendis mollitia at fuga expedita soluta veniam reprehenderit cupiditate id animi tempore eum nihil repellendus illum doloremque aut, suscipit corrupti eaque porro ut, beatae, quis dolores. Nesciunt, porro! Soluta fugit sunt sit in praesentium ut architecto esse quisquam dolore dolores delectus reiciendis eos pariatur aperiam expedita tempore qui itaque facilis dolorum sint, eligendi officiis repudiandae rem. Illum, natus? Nostrum animi laborum quidem ab aspernatur, facilis
        exercitationem mollitia voluptates repudiandae ullam, id sit debitis dolorem culpa quis voluptate officiis, eius possimus expedita. Recusandae, neque nostrum! Excepturi, minima? Quam, quasi. Qui officia expedita repellendus explicabo, ullam rerum nostrum sed dicta corporis quam cupiditate, facere quisquam? Velit magni modi doloremque unde hic error perferendis non excepturi a. Aut placeat aliquam eaque! At est modi cupiditate illo. Dolores perferendis iste quia necessitatibus similique
        harum! Voluptatum unde incidunt praesentium a beatae perferendis explicabo dolores accusantium cum, quod eius velit et quidem qui odit. Aliquid sint repellendus fugit. Officiis deleniti sint consequuntur aliquid neque commodi asperiores eum non, voluptatum odit? Ab consequatur repudiandae tenetur recusandae, atque totam sunt soluta. Exercitationem quae rem sapiente reprehenderit. Quae veritatis expedita blanditiis voluptatibus itaque animi error quis ex at perspiciatis natus maiores unde
        pariatur fugit aperiam repudiandae debitis earum eius nihil doloremque aspernatur similique, libero laudantium. Eaque, ipsa. Eaque voluptate, odio pariatur libero hic recusandae totam quaerat quibusdam, deleniti placeat consequatur eligendi quod officia exercitationem inventore? Modi veniam maxime voluptates ex doloremque ipsam est error accusamus obcaecati maiores. Consectetur pariatur veritatis assumenda dolorem non architecto quaerat accusamus temporibus consequuntur sapiente,
        laboriosam laborum? Accusamus adipisci rem tenetur ipsa placeat vitae quas aut neque! Quaerat eius adipisci veniam iure rerum. Ipsam hic nemo cum nisi aliquam minima, vel maiores architecto iusto sit fuga rerum asperiores sequi id quidem accusantium laborum, molestias facere, nulla pariatur. Cum architecto dolorum quis fugit magni! Corporis placeat voluptas libero, perspiciatis repellendus iste, ut numquam possimus cum consectetur necessitatibus deleniti culpa non quas? Incidunt, ducimus
        beatae deleniti explicabo illo illum doloribus dignissimos repudiandae, expedita tempore a. Laborum suscipit numquam, rerum ea porro vitae quasi natus veritatis repudiandae dignissimos cupiditate ullam maiores, ipsa magni beatae ad corrupti facere earum deserunt nihil itaque. Asperiores doloremque laudantium soluta consectetur. Distinctio voluptate est earum dolores aut eligendi eveniet, eum voluptates voluptatem illo necessitatibus blanditiis amet hic harum labore officiis atque fugiat
        maiores at, sit illum cupiditate magnam? Sequi, modi veniam! Nam officia nesciunt, atque vitae beatae cupiditate quia architecto incidunt autem deserunt animi iure natus ut perspiciatis quae eveniet maxime quisquam vel porro ullam provident? Tempore, corrupti? Officia, odit eum! Quasi dicta id, aspernatur animi qui laudantium perferendis recusandae? Quae dolores commodi reiciendis facere veniam doloribus quasi unde? Ratione ipsam eum dicta quo magni aspernatur accusamus expedita facere
        nulla officia? Eligendi excepturi, repudiandae, minus sit libero itaque magni dolores reiciendis eum ad, assumenda delectus exercitationem ratione qui et accusamus placeat aliquid eveniet! Fugiat incidunt quasi et aliquam! Laborum, illo sed. Deleniti voluptate dolorum, sequi provident quam perspiciatis architecto porro vero temporibus minima maiores magnam, molestias dolore nulla possimus a commodi distinctio exercitationem officia nesciunt ducimus. Asperiores magnam mollitia repellat
        eum. Id nobis sed voluptatibus quisquam reiciendis sint quod repudiandae molestiae illum laudantium quam at nam recusandae ut, dolorem minus esse mollitia, iste vitae commodi maxime ratione est pariatur molestias. Perspiciatis. Debitis optio non nobis excepturi sit veniam nihil nemo odio ad sed ipsum illo porro dolorum, autem natus cum qui aut sequi. In maxime ab aperiam dolorem, ex impedit unde? Mollitia alias praesentium necessitatibus hic facilis culpa vitae voluptatum, repudiandae
        tempora, debitis id quasi recusandae inventore, ab delectus? Corporis dolorem atque nostrum inventore possimus dignissimos vero libero aliquid repellendus voluptas. Similique explicabo ducimus aliquam ut nobis dolorum ex accusamus amet soluta eveniet debitis, rem enim repellat autem, distinctio blanditiis voluptatum corrupti tempora suscipit! Sapiente cum numquam repellendus distinctio, iusto minus. Doloremque, vero molestiae consectetur atque repellendus labore quam iusto illum ad
        tenetur doloribus deserunt placeat earum itaque? Minima maxime perferendis accusamus perspiciatis tenetur reiciendis ducimus laboriosam, unde dolores at dolorum. Accusamus velit voluptas eos! Praesentium nulla tempore accusantium. Ex recusandae eum facere quia nobis illum commodi voluptatum rem id ullam. Dolorem deleniti ut a quae iusto culpa sequi voluptate mollitia. Esse, ad! Nam enim ipsum provident, asperiores, doloribus nemo porro qui minus, doloremque sunt voluptates. Voluptate
        porro, delectus assumenda, aspernatur numquam, sed nam praesentium blanditiis inventore ipsa perspiciatis hic ratione! Sed vel veritatis ab praesentium cum saepe eos eligendi dolores est iste. Ratione, dolor! Accusamus explicabo quibusdam sint, vitae aliquam cum ipsa corporis atque assumenda porro voluptates, tempora tempore deleniti? Unde aut rem nam. Ea tempora eaque ut voluptatibus, omnis sapiente commodi laborum nulla vitae facilis hic recusandae. Assumenda sapiente dicta quo officia
        consectetur, libero aliquam doloribus. Laboriosam, explicabo sequi. Dolores laudantium eaque, autem ducimus reprehenderit ut pariatur aliquid sapiente illo facilis similique omnis repellendus earum! Assumenda nam velit nemo, eveniet alias temporibus debitis itaque, officia aperiam corporis veniam tempora? Eligendi ipsam, voluptate quod dolor, ea ipsa possimus ducimus animi exercitationem, velit similique enim veniam quos est delectus quasi quo eveniet officia quibusdam! Ducimus hic, ipsa
        fugiat ratione veniam reprehenderit. Rerum earum reiciendis assumenda eos dolor quos optio ratione adipisci quis repellendus! Quo placeat rem molestiae illo tempora nobis alias, natus in? Nisi numquam cumque consequatur temporibus qui facilis vero. Dicta saepe, maxime aliquid autem vel unde laboriosam modi fugit. Exercitationem voluptas similique cumque. Itaque alias nihil, quisquam maxime assumenda optio quo nobis, voluptatibus quae numquam, molestiae voluptate quaerat maiores? Eum
        ipsa, suscipit alias commodi repudiandae quos, error labore maxime asperiores atque praesentium ea sequi, ullam iure! Reiciendis, laborum, magni perspiciatis, nostrum voluptatum eius placeat officiis molestiae odio repellendus dolorem. Quam tenetur recusandae debitis omnis optio nostrum autem voluptate? Nam unde reprehenderit dolor commodi sunt corrupti cumque eum. Blanditiis et eveniet esse dolores maxime quibusdam dolorum ducimus voluptate, ex consequatur. Sed quas ullam sapiente
        quibusdam dolores asperiores eum at, enim odio quaerat non voluptas corporis doloremque! Aliquid nam quaerat totam, ea dolorum dicta possimus veniam iure, corrupti nesciunt est eius? Nesciunt, adipisci quos. Non, natus! Quia iusto quos corporis omnis maxime alias ipsam cupiditate possimus fuga maiores saepe porro architecto, nam sequi molestiae minima id molestias doloribus inventore quibusdam? Quod. Facilis tenetur laudantium fugit quis eum doloribus iste dolore, itaque animi soluta,
        reiciendis nostrum in alias enim reprehenderit harum autem debitis sapiente dolorem suscipit architecto ad deleniti quasi! Alias, iste! Laboriosam repellat sit omnis voluptates, doloremque provident labore quae ipsum dolor fugit molestiae eius quam at consequuntur debitis perferendis earum hic sint necessitatibus magnam? Quaerat quam corporis eos aliquam sequi. Modi, officia qui architecto numquam quia dolore. Quisquam, qui facilis dignissimos assumenda dolorem in! Corporis sed molestias
        atque exercitationem aut architecto, nostrum consequuntur impedit ab sequi fugiat sit officiis reiciendis.
      </p>
    </main>
  );
};

export default BodyHome;
